[project]
name = "vem"
version = "0.2.0"
description = "Menubar icon for vim emulation"
authors = [ { name = "rcmdnk", email = "rcmdnk@gmail.com" } ]
readme = "README.md"
license = "Apache-2.0"
keywords = []
classifiers = []
requires-python = ">=3.10,<4.0"
dependencies = [
    "py2app>=0.28.10",
    "rumps>=0.4.0",
]

[project.urls]
Repository = "https://github.com/rcmdnk/VEM"
Documentation = "https://github.com/rcmdnk/VEM"
Homepage = "https://github.com/rcmdnk/VEM"
Issue = "https://github.com/rcmdnk/VEM/issues"

[dependency-groups]
dev = []

[build-system]
requires = ["uv_build>=0.11.2,<0.12"]
build-backend = "uv_build"

[tool.uv]
exclude-newer = "1 week"
